### ISSUE TITLE
支持多数据库连接

### ISSUE THREAD

**Issue by ooopSnake** [gen-iot/bootx#5]
缺陷:
目前只支持连接一个数据库,现在希望能连接更多的数据库

期望配置:
```yaml
database:
 - 
  name: public
  default: true
  databaseType: postgres
  connStr: "some url"
  showSql: true
  maxIdleConn: 2
  maxOpenConn: 5
 - 
  name: private
  databaseType: mysql
  connStr: "some url"
  showSql: true
  maxIdleConn: 5
  maxOpenConn: 10

```

提供根据name获取对应的连接的api

```go
func bootx.Db() (*gorm.Db,error) // get default database
func bootx.Db2(name string) (*gorm.Db,error) // get database by name
```
